add_test( MockSupportTestWithFixture C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockSupportTestWithFixture)
set_tests_properties( MockSupportTestWithFixture PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockSupportTest.cpp:205)
add_test( MockSupportTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockSupportTest)
set_tests_properties( MockSupportTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockSupportTest.cpp:49)
add_test( MockStrictOrderTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockStrictOrderTest)
set_tests_properties( MockStrictOrderTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockStrictOrderTest.cpp:39)
add_test( MockFailureTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockFailureTest)
set_tests_properties( MockFailureTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockFailureTest.cpp:110)
add_test( MockParameterTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockParameterTest)
set_tests_properties( MockParameterTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockParameterTest.cpp:41)
add_test( MockCallTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockCallTest)
set_tests_properties( MockCallTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockCallTest.cpp:41)
add_test( MockSupport_c C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockSupport_c)
set_tests_properties( MockSupport_c PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockSupport_cTest.cpp:52)
add_test( MockPlugin C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockPlugin)
set_tests_properties( MockPlugin PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockPluginTest.cpp:58)
add_test( MockNamedValue C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockNamedValue)
set_tests_properties( MockNamedValue PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockNamedValueTest.cpp:110)
add_test( ComparatorsAndCopiersRepository C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg ComparatorsAndCopiersRepository)
set_tests_properties( ComparatorsAndCopiersRepository PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockNamedValueTest.cpp:56)
add_test( MockReturnValueTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockReturnValueTest)
set_tests_properties( MockReturnValueTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockReturnValueTest.cpp:40)
add_test( TestOrderedTestMacros C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg TestOrderedTestMacros)
set_tests_properties( TestOrderedTestMacros PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/OrderedTestTest.cpp:178)
add_test( TestOrderedTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg TestOrderedTest)
set_tests_properties( TestOrderedTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/OrderedTestTest.cpp:83)
add_test( CodeMemoryReportFormatter C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg CodeMemoryReportFormatter)
set_tests_properties( CodeMemoryReportFormatter PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/CodeMemoryReporterTest.cpp:68)
add_test( MockHierarchyTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockHierarchyTest)
set_tests_properties( MockHierarchyTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockHierarchyTest.cpp:39)
add_test( MockIgnoredExpectedCall C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockIgnoredExpectedCall)
set_tests_properties( MockIgnoredExpectedCall PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockExpectedCallTest.cpp:772)
add_test( MockExpectedCall C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockExpectedCall)
set_tests_properties( MockExpectedCall PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockExpectedCallTest.cpp:173)
add_test( MockNamedValueHandlerRepository C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockNamedValueHandlerRepository)
set_tests_properties( MockNamedValueHandlerRepository PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockExpectedCallTest.cpp:83)
add_test( MockComparatorCopierTest C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockComparatorCopierTest)
set_tests_properties( MockComparatorCopierTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockComparatorCopierTest.cpp:82)
add_test( MockCheatSheet C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockCheatSheet)
set_tests_properties( MockCheatSheet PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockCheatSheetTest.cpp:51)
add_test( MockCheckedActualCall C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockCheckedActualCall)
set_tests_properties( MockCheckedActualCall PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MockActualCallTest.cpp:59)
add_test( MemoryReporterPlugin C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MemoryReporterPlugin)
set_tests_properties( MemoryReporterPlugin PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MemoryReporterPluginTest.cpp:151)
add_test( NormalMemoryReportFormatter C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg NormalMemoryReportFormatter)
set_tests_properties( NormalMemoryReportFormatter PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MemoryReportFormatterTest.cpp:56)
add_test( MemoryReportAllocator C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MemoryReportAllocator)
set_tests_properties( MemoryReportAllocator PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/MemoryReportAllocatorTest.cpp:38)
add_test( MockExpectedCallsList C:/Projects/cpputest/cpputeste_build/tests/CppUTestExt/Debug/CppUTestExtTests.exe -v -sg MockExpectedCallsList)
set_tests_properties( MockExpectedCallsList PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTestExt/ExpectedFunctionsListTest.cpp:64)
