add_test( UnitTestStringMacros C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UnitTestStringMacros)
set_tests_properties( UnitTestStringMacros PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestUTestStringMacro.cpp:44)
add_test( UtestShellPointerArrayTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UtestShellPointerArrayTest)
set_tests_properties( UtestShellPointerArrayTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestTest.cpp:611)
add_test( CanHaveMemberVariablesInTestGroupThatAllocateMemoryWithoutCausingMemoryLeaks C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg CanHaveMemberVariablesInTestGroupThatAllocateMemoryWithoutCausingMemoryLeaks)
set_tests_properties( CanHaveMemberVariablesInTestGroupThatAllocateMemoryWithoutCausingMemoryLeaks PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestTest.cpp:571)
add_test( UtestMyOwn C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UtestMyOwn)
set_tests_properties( UtestMyOwn PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestTest.cpp:528)
add_test( IgnoredUtestShell C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg IgnoredUtestShell)
set_tests_properties( IgnoredUtestShell PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestTest.cpp:440)
add_test( UtestShell C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UtestShell)
set_tests_properties( UtestShell PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestTest.cpp:63)
add_test( UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess)
set_tests_properties( UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/UtestPlatformTest.cpp:50)
add_test( UnitTestMacros C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg UnitTestMacros)
set_tests_properties( UnitTestMacros PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestUTestMacro.cpp:57)
add_test( GlobalMemoryAccountant C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg GlobalMemoryAccountant)
set_tests_properties( GlobalMemoryAccountant PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:644)
add_test( AccountingTestMemoryAllocator C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg AccountingTestMemoryAllocator)
set_tests_properties( AccountingTestMemoryAllocator PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:560)
add_test( TestMemoryAccountant C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestMemoryAccountant)
set_tests_properties( TestMemoryAccountant PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:366)
add_test( FailableMemoryAllocator C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg FailableMemoryAllocator)
set_tests_properties( FailableMemoryAllocator PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:233)
add_test( MemoryLeakAllocator C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakAllocator)
set_tests_properties( MemoryLeakAllocator PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:163)
add_test( TestMemoryAllocatorTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestMemoryAllocatorTest)
set_tests_properties( TestMemoryAllocatorTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestMemoryAllocatorTest.cpp:52)
add_test( TestInstaller C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestInstaller)
set_tests_properties( TestInstaller PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestInstallerTest.cpp:60)
add_test( TestHarness_c C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestHarness_c)
set_tests_properties( TestHarness_c PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestHarness_cTest.cpp:93)
add_test( TestGroupInC C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestGroupInC)
set_tests_properties( TestGroupInC PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestHarness_cTest.cpp:48)
add_test( TestFilter C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestFilter)
set_tests_properties( TestFilter PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestFilterTest.cpp:35)
add_test( OutOfMemoryTestsForOperatorNew C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg OutOfMemoryTestsForOperatorNew)
set_tests_properties( OutOfMemoryTestsForOperatorNew PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryOperatorOverloadTest.cpp:330)
add_test( TestForExceptionsInConstructor C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestForExceptionsInConstructor)
set_tests_properties( TestForExceptionsInConstructor PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryOperatorOverloadTest.cpp:344)
add_test( MemoryLeakOverridesToBeUsedInProductionCode C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakOverridesToBeUsedInProductionCode)
set_tests_properties( MemoryLeakOverridesToBeUsedInProductionCode PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryOperatorOverloadTest.cpp:71)
add_test( BasicBehavior C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg BasicBehavior)
set_tests_properties( BasicBehavior PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryOperatorOverloadTest.cpp:18)
add_test( TestRegistry C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestRegistry)
set_tests_properties( TestRegistry PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestRegistryTest.cpp:155)
add_test( CompositeTestOutput C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg CompositeTestOutput)
set_tests_properties( CompositeTestOutput PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestOutputTest.cpp:359)
add_test( TestOutput C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestOutput)
set_tests_properties( TestOutput PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestOutputTest.cpp:87)
add_test( GlobalSimpleStringCache C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg GlobalSimpleStringCache)
set_tests_properties( GlobalSimpleStringCache PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleStringCacheTest.cpp:380)
add_test( SimpleStringCacheAllocator C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SimpleStringCacheAllocator)
set_tests_properties( SimpleStringCacheAllocator PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleStringCacheTest.cpp:347)
add_test( SimpleStringInternalCache C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SimpleStringInternalCache)
set_tests_properties( SimpleStringInternalCache PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleStringCacheTest.cpp:82)
add_test( SimpleString C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SimpleString)
set_tests_properties( SimpleString PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleStringTest.cpp:171)
add_test( GlobalSimpleStringMemoryAccountant C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg GlobalSimpleStringMemoryAccountant)
set_tests_properties( GlobalSimpleStringMemoryAccountant PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleStringTest.cpp:83)
add_test( ReallocBugReported C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg ReallocBugReported)
set_tests_properties( ReallocBugReported PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakDetectorTest.cpp:678)
add_test( SimpleStringBuffer C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SimpleStringBuffer)
set_tests_properties( SimpleStringBuffer PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakDetectorTest.cpp:568)
add_test( MemoryLeakDetectorListTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakDetectorListTest)
set_tests_properties( MemoryLeakDetectorListTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakDetectorTest.cpp:549)
add_test( MemoryLeakDetectorTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakDetectorTest)
set_tests_properties( MemoryLeakDetectorTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakDetectorTest.cpp:132)
add_test( TestResult C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestResult)
set_tests_properties( TestResult PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestResultTest.cpp:62)
add_test( TestFailure C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestFailure)
set_tests_properties( TestFailure PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestFailureTest.cpp:52)
add_test( TestFailureNanAndInf C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TestFailureNanAndInf)
set_tests_properties( TestFailureNanAndInf PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TestFailureNaNTest.cpp:59)
add_test( TeamCityOutputTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg TeamCityOutputTest)
set_tests_properties( TeamCityOutputTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/TeamCityOutputTest.cpp:78)
add_test( SimpleMutexTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SimpleMutexTest)
set_tests_properties( SimpleMutexTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SimpleMutexTest.cpp:80)
add_test( SetPointerPluginTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg SetPointerPluginTest)
set_tests_properties( SetPointerPluginTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/SetPluginTest.cpp:77)
add_test( PluginTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg PluginTest)
set_tests_properties( PluginTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/PluginTest.cpp:113)
add_test( MemoryLeakWarningThreadSafe C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakWarningThreadSafe)
set_tests_properties( MemoryLeakWarningThreadSafe PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakWarningTest.cpp:424)
add_test( MemoryLeakWarningGlobalDetectorTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakWarningGlobalDetectorTest)
set_tests_properties( MemoryLeakWarningGlobalDetectorTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakWarningTest.cpp:231)
add_test( MemoryLeakWarningTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakWarningTest)
set_tests_properties( MemoryLeakWarningTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakWarningTest.cpp:110)
add_test( MemoryLeakWarningLocalDetectorTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg MemoryLeakWarningLocalDetectorTest)
set_tests_properties( MemoryLeakWarningLocalDetectorTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/MemoryLeakWarningTest.cpp:44)
add_test( JUnitOutputTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg JUnitOutputTest)
set_tests_properties( JUnitOutputTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/JUnitOutputTest.cpp:368)
add_test( RunIgnoredTest C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg RunIgnoredTest)
set_tests_properties( RunIgnoredTest PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/CommandLineTestRunnerTest.cpp:441)
add_test( CommandLineTestRunner C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg CommandLineTestRunner)
set_tests_properties( CommandLineTestRunner PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/CommandLineTestRunnerTest.cpp:119)
add_test( CommandLineArguments C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg CommandLineArguments)
set_tests_properties( CommandLineArguments PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/CommandLineArgumentsTest.cpp:71)
add_test( CheatSheet C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg CheatSheet)
set_tests_properties( CheatSheet PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/CheatSheetTest.cpp:25)
add_test( AllocLetTestFree C:/Projects/cpputest/cpputeste_build/tests/CppUTest/Debug/CppUTestTests.exe -v -sg AllocLetTestFree)
set_tests_properties( AllocLetTestFree PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/tests/CppUTest/AllocLetTestFreeTest.cpp:30)
