add_test( Printer C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg Printer)
set_tests_properties( Printer PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/PrinterTest.cpp:48)
add_test( BarTestGroup C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg BarTestGroup)
set_tests_properties( BarTestGroup PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/MockDocumentationTest.cpp:231)
add_test( FooTestGroup C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg FooTestGroup)
set_tests_properties( FooTestGroup PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/MockDocumentationTest.cpp:213)
add_test( MockDocumentation C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg MockDocumentation)
set_tests_properties( MockDocumentation PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/MockDocumentationTest.cpp:55)
add_test( FirstTestGroup C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg FirstTestGroup)
set_tests_properties( FirstTestGroup PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/MockDocumentationTest.cpp:36)
add_test( HelloWorld C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg HelloWorld)
set_tests_properties( HelloWorld PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/HelloTest.cpp:57)
add_test( EventDispatcher C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg EventDispatcher)
set_tests_properties( EventDispatcher PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/EventDispatcherTest.cpp:92)
add_test( CircularBuffer C:/Projects/cpputest/cpputeste_build/examples/AllTests/Debug/ExampleTests.exe -v -sg CircularBuffer)
set_tests_properties( CircularBuffer PROPERTIES DEF_SOURCE_LINE C:/Projects/cpputest/examples/AllTests/CircularBufferTest.cpp:57)
